/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyHealthData {
  'sleepQuality' : [] | [number],
  'veggies' : [] | [number],
  'date' : string,
  'calories' : [] | [number],
  'restingHr' : [] | [number],
  'systolic' : [] | [number],
  'sport' : [] | [string],
  'fastingStart' : [] | [string],
  'movementDuration' : [] | [number],
  'fastingEnd' : [] | [string],
  'diastolic' : [] | [number],
  'water' : [] | [number],
  'intensity' : [] | [number],
  'protein' : [] | [number],
  'sleepDuration' : [] | [number],
}
export interface DiaryEntry {
  'id' : bigint,
  'text' : string,
  'timestamp' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface RoutineWithStatus {
  'id' : bigint,
  'title' : string,
  'done' : boolean,
  'createdAt' : bigint,
  'time' : string,
  'description' : string,
}
export interface ScoreEntry { 'date' : string, 'score' : number }
export interface SubscriptionEntry {
  'expiryDate' : bigint,
  'user' : Principal,
  'isActive' : boolean,
}
export interface SubscriptionStatus {
  'expiryDate' : [] | [bigint],
  'isActive' : boolean,
}
export interface UserProfile {
  'heightCm' : [] | [bigint],
  'bodyFatPct' : [] | [number],
  'birthYear' : [] | [bigint],
  'name' : string,
  'weightKg' : [] | [number],
  'gender' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSubscription' : ActorMethod<[bigint], Result>,
  'addDiaryEntry' : ActorMethod<[string, string], Result>,
  'adminActivateSubscription' : ActorMethod<[Principal], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkSubscription' : ActorMethod<[], SubscriptionStatus>,
  'claimFounderLivTokens' : ActorMethod<[], Result>,
  'createRoutine' : ActorMethod<[string, string, string], Result>,
  'deleteDiaryEntry' : ActorMethod<[bigint], Result>,
  'deleteRoutine' : ActorMethod<[bigint], Result>,
  'getAdminSubscriptionList' : ActorMethod<[], Array<SubscriptionEntry>>,
  'getAllHealthData' : ActorMethod<[], Array<DailyHealthData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyHealthData' : ActorMethod<[string], [] | [DailyHealthData]>,
  'getDiaryEntriesForCaller' : ActorMethod<[], Array<DiaryEntry>>,
  'getLivBalance' : ActorMethod<[Principal], bigint>,
  'getLivTokenInfo' : ActorMethod<
    [],
    { 'decimals' : bigint, 'name' : string, 'symbol' : string }
  >,
  'getMyLivBalance' : ActorMethod<[], bigint>,
  'getRoutinesForCaller' : ActorMethod<[], Array<RoutineWithStatus>>,
  'getScoreHistoryForCaller' : ActorMethod<[], Array<ScoreEntry>>,
  'getScoreHistoryForUser' : ActorMethod<[Principal], Array<ScoreEntry>>,
  'getSingleRoutine' : ActorMethod<[bigint], RoutineWithStatus>,
  'getTotalLivSupply' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRoutineDone' : ActorMethod<[bigint, string], Result>,
  'markRoutineUndone' : ActorMethod<[bigint], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyHealthData' : ActorMethod<
    [
      string,
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
      [] | [string],
      [] | [number],
    ],
    Result
  >,
  'saveDailyScore' : ActorMethod<[string, number], Result>,
  'transferLiv' : ActorMethod<[Principal, bigint], Result>,
  'updateDiaryEntry' : ActorMethod<[bigint, string], Result>,
  'updateRoutine' : ActorMethod<[bigint, string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];