/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RoutineWithStatus = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'done' : IDL.Bool,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoutine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'deleteRoutine' : IDL.Func([IDL.Nat], [Result], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRoutinesForCaller' : IDL.Func(
      [],
      [IDL.Vec(RoutineWithStatus)],
      ['query'],
    ),
  'getSingleRoutine' : IDL.Func([IDL.Nat], [RoutineWithStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRoutineDone' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'markRoutineUndone' : IDL.Func([IDL.Nat], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRoutine' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RoutineWithStatus = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'done' : IDL.Bool,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoutine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'deleteRoutine' : IDL.Func([IDL.Nat], [Result], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRoutinesForCaller' : IDL.Func(
        [],
        [IDL.Vec(RoutineWithStatus)],
        ['query'],
      ),
    'getSingleRoutine' : IDL.Func([IDL.Nat], [RoutineWithStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRoutineDone' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'markRoutineUndone' : IDL.Func([IDL.Nat], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRoutine' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };