/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Result = { 'ok' : null } |
  { 'err' : string };
export interface RoutineWithStatus {
  'id' : bigint,
  'title' : string,
  'done' : boolean,
  'createdAt' : bigint,
  'time' : string,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoutine' : ActorMethod<[string, string, string], Result>,
  'deleteRoutine' : ActorMethod<[bigint], Result>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRoutinesForCaller' : ActorMethod<[], Array<RoutineWithStatus>>,
  'getSingleRoutine' : ActorMethod<[bigint], RoutineWithStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRoutineDone' : ActorMethod<[bigint, string], Result>,
  'markRoutineUndone' : ActorMethod<[bigint], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRoutine' : ActorMethod<[bigint, string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];