/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyHealthData {
    sleepQuality?: number;
    veggies?: number;
    date: string;
    calories?: number;
    restingHr?: number;
    systolic?: number;
    sport?: string;
    fastingStart?: string;
    movementDuration?: number;
    fastingEnd?: string;
    diastolic?: number;
    water?: number;
    intensity?: number;
    protein?: number;
    sleepDuration?: number;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface ScoreEntry {
    date: string;
    score: number;
}
export interface SubscriptionEntry {
    expiryDate: bigint;
    user: Principal;
    isActive: boolean;
}
export interface DiaryEntry {
    id: bigint;
    text: string;
    timestamp: string;
}
export interface RoutineWithStatus {
    id: bigint;
    title: string;
    done: boolean;
    createdAt: bigint;
    time: string;
    description: string;
}
export interface SubscriptionStatus {
    expiryDate?: bigint;
    isActive: boolean;
}
export interface UserProfile {
    heightCm?: bigint;
    bodyFatPct?: number;
    birthYear?: bigint;
    name: string;
    weightKg?: number;
    gender?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateSubscription(blockIndex: bigint): Promise<Result>;
    addDiaryEntry(text: string, timestamp: string): Promise<Result>;
    adminActivateSubscription(user: Principal): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkSubscription(): Promise<SubscriptionStatus>;
    claimFounderLivTokens(): Promise<Result>;
    createRoutine(title: string, time: string, description: string): Promise<Result>;
    deleteDiaryEntry(id: bigint): Promise<Result>;
    deleteRoutine(id: bigint): Promise<Result>;
    getAdminSubscriptionList(): Promise<Array<SubscriptionEntry>>;
    getAllHealthData(): Promise<Array<DailyHealthData>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyHealthData(date: string): Promise<DailyHealthData | null>;
    getDiaryEntriesForCaller(): Promise<Array<DiaryEntry>>;
    getLivBalance(p: Principal): Promise<bigint>;
    getLivTokenInfo(): Promise<{
        decimals: bigint;
        name: string;
        symbol: string;
    }>;
    getMyLivBalance(): Promise<bigint>;
    getRoutinesForCaller(): Promise<Array<RoutineWithStatus>>;
    getScoreHistoryForCaller(): Promise<Array<ScoreEntry>>;
    getScoreHistoryForUser(user: Principal): Promise<Array<ScoreEntry>>;
    getSingleRoutine(id: bigint): Promise<RoutineWithStatus>;
    getTotalLivSupply(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markRoutineDone(id: bigint, date: string): Promise<Result>;
    markRoutineUndone(id: bigint): Promise<Result>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyHealthData(date: string, sleepDuration: number | null, sleepQuality: number | null, protein: number | null, veggies: number | null, water: number | null, sport: string | null, intensity: number | null, movementDuration: number | null, systolic: number | null, diastolic: number | null, restingHr: number | null, fastingStart: string | null, fastingEnd: string | null, calories: number | null): Promise<Result>;
    saveDailyScore(date: string, score: number): Promise<Result>;
    transferLiv(to: Principal, amount: bigint): Promise<Result>;
    updateDiaryEntry(id: bigint, text: string): Promise<Result>;
    updateRoutine(id: bigint, title: string, time: string, description: string): Promise<Result>;
}
import type { DailyHealthData as _DailyHealthData, Result as _Result, SubscriptionStatus as _SubscriptionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateSubscription(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscription(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscription(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDiaryEntry(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addDiaryEntry(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDiaryEntry(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminActivateSubscription(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminActivateSubscription(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminActivateSubscription(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkSubscription(): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscription();
                return from_candid_SubscriptionStatus_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscription();
            return from_candid_SubscriptionStatus_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimFounderLivTokens(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFounderLivTokens();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFounderLivTokens();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoutine(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoutine(arg0, arg1, arg2);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoutine(arg0, arg1, arg2);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDiaryEntry(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDiaryEntry(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDiaryEntry(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRoutine(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoutine(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoutine(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminSubscriptionList(): Promise<Array<SubscriptionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSubscriptionList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSubscriptionList();
            return result;
        }
    }
    async getAllHealthData(): Promise<Array<DailyHealthData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHealthData();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHealthData();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyHealthData(arg0: string): Promise<DailyHealthData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyHealthData(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyHealthData(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiaryEntriesForCaller(): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaryEntriesForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaryEntriesForCaller();
            return result;
        }
    }
    async getLivBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivBalance(arg0);
            return result;
        }
    }
    async getLivTokenInfo(): Promise<{
        decimals: bigint;
        name: string;
        symbol: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivTokenInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivTokenInfo();
            return result;
        }
    }
    async getMyLivBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLivBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLivBalance();
            return result;
        }
    }
    async getRoutinesForCaller(): Promise<Array<RoutineWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutinesForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutinesForCaller();
            return result;
        }
    }
    async getScoreHistoryForCaller(): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreHistoryForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreHistoryForCaller();
            return result;
        }
    }
    async getScoreHistoryForUser(arg0: Principal): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreHistoryForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreHistoryForUser(arg0);
            return result;
        }
    }
    async getSingleRoutine(arg0: bigint): Promise<RoutineWithStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSingleRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSingleRoutine(arg0);
            return result;
        }
    }
    async getTotalLivSupply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLivSupply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLivSupply();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markRoutineDone(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markRoutineDone(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRoutineDone(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRoutineUndone(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markRoutineUndone(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRoutineUndone(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDailyHealthData(arg0: string, arg1: number | null, arg2: number | null, arg3: number | null, arg4: number | null, arg5: number | null, arg6: string | null, arg7: number | null, arg8: number | null, arg9: number | null, arg10: number | null, arg11: number | null, arg12: string | null, arg13: string | null, arg14: number | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyHealthData(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg14));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyHealthData(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg14));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDailyScore(arg0: string, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyScore(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyScore(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferLiv(arg0: Principal, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.transferLiv(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferLiv(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDiaryEntry(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDiaryEntry(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDiaryEntry(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRoutine(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoutine(arg0, arg1, arg2, arg3);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoutine(arg0, arg1, arg2, arg3);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DailyHealthData_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyHealthData): DailyHealthData {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyHealthData]): DailyHealthData | null {
    return value.length === 0 ? null : from_candid_DailyHealthData_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sleepQuality: [] | [number];
    veggies: [] | [number];
    date: string;
    calories: [] | [number];
    restingHr: [] | [number];
    systolic: [] | [number];
    sport: [] | [string];
    fastingStart: [] | [string];
    movementDuration: [] | [number];
    fastingEnd: [] | [string];
    diastolic: [] | [number];
    water: [] | [number];
    intensity: [] | [number];
    protein: [] | [number];
    sleepDuration: [] | [number];
}): {
    sleepQuality?: number;
    veggies?: number;
    date: string;
    calories?: number;
    restingHr?: number;
    systolic?: number;
    sport?: string;
    fastingStart?: string;
    movementDuration?: number;
    fastingEnd?: string;
    diastolic?: number;
    water?: number;
    intensity?: number;
    protein?: number;
    sleepDuration?: number;
} {
    return {
        sleepQuality: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.sleepQuality)),
        veggies: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.veggies)),
        date: value.date,
        calories: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.calories)),
        restingHr: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.restingHr)),
        systolic: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.systolic)),
        sport: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.sport)),
        fastingStart: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.fastingStart)),
        movementDuration: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.movementDuration)),
        fastingEnd: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.fastingEnd)),
        diastolic: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.diastolic)),
        water: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.water)),
        intensity: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.intensity)),
        protein: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.protein)),
        sleepDuration: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.sleepDuration))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm: [] | [bigint];
    bodyFatPct: [] | [number];
    birthYear: [] | [bigint];
    name: string;
    weightKg: [] | [number];
    gender: [] | [string];
}): {
    heightCm?: bigint;
    bodyFatPct?: number;
    birthYear?: bigint;
    name: string;
    weightKg?: number;
    gender?: string;
} {
    return {
        heightCm: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.heightCm)),
        bodyFatPct: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bodyFatPct)),
        birthYear: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.birthYear)),
        name: value.name,
        weightKg: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.weightKg)),
        gender: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.gender))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: [] | [bigint];
    isActive: boolean;
}): {
    expiryDate?: bigint;
    isActive: boolean;
} {
    return {
        expiryDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expiryDate)),
        isActive: value.isActive
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyHealthData>): Array<DailyHealthData> {
    return value.map((x)=>from_candid_DailyHealthData_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm?: bigint;
    bodyFatPct?: number;
    birthYear?: bigint;
    name: string;
    weightKg?: number;
    gender?: string;
}): {
    heightCm: [] | [bigint];
    bodyFatPct: [] | [number];
    birthYear: [] | [bigint];
    name: string;
    weightKg: [] | [number];
    gender: [] | [string];
} {
    return {
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        bodyFatPct: value.bodyFatPct ? candid_some(value.bodyFatPct) : candid_none(),
        birthYear: value.birthYear ? candid_some(value.birthYear) : candid_none(),
        name: value.name,
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
